/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

module bfsk(reset, clk, bfsk_out);

  wire _0_;
  wire _1_;
  wire [6:0] _2_;
  wire [6:0] _3_;
  wire _4_;
  wire [6:0] _5_;
  output [6:0] bfsk_out;
  wire [6:0] bfsk_out;
  input clk;
  wire clk;
  input reset;
  wire reset;
  wire sig_clk_1mhz;
  wire sig_clk_25mhz;
  wire sig_data;
  wire [6:0] sig_wave1;
  wire [6:0] sig_wave2;

  clk_rdg2 instance1 (
    .clk_in(clk),
    .clk_out(_0_),
    .reset(reset)
  );
  clk_25MHz instance2 (
    .clk_in(clk),
    .clk_out(_1_),
    .reset(reset)
  );
  wave12 instance3 (
    .clk(clk),
    .dataout(_2_),
    .reset(reset)
  );
  wave22 instance4 (
    .clk(sig_clk_25mhz),
    .dataout(_3_),
    .reset(reset)
  );
  rdg2 instance5 (
    .clk(sig_clk_1mhz),
    .data(_4_),
    .reset(reset)
  );
  freq_select instance6 (
    .clk_1(sig_wave1),
    .clk_2(sig_wave2),
    .data(sig_data),
    .freq_out(_5_)
  );
  assign sig_clk_25mhz = _1_;
  assign sig_clk_1mhz = _0_;
  assign sig_data = _4_;
  assign sig_wave1 = _2_;
  assign sig_wave2 = _3_;
  assign bfsk_out = _5_;
endmodule
