/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

module bpsk(reset, clk, bpsk_out);

  wire _0_;
  wire _1_;
  wire [6:0] _2_;
  wire [6:0] _3_;
  wire [6:0] _4_;
  output [6:0] bpsk_out;
  wire [6:0] bpsk_out;
  input clk;
  wire clk;
  input reset;
  wire reset;
  wire [6:0] sig_bpsk_out;
  wire sig_clk_1mhz;
  wire sig_data2;
  wire [6:0] sig_wave1;
  wire [6:0] sig_wave2;
  assign _4_ = sig_data2 ? sig_wave1 : sig_wave2;

  clk_rdg3 instance1 (
    .clk_in(clk),
    .clk_out(_0_),
    .reset(reset)
  );
  rdg3 instance2 (
    .clk(sig_clk_1mhz),
    .data(_1_),
    .reset(reset)
  );
  wave13 instance3 (
    .clk(clk),
    .dataout(_2_),
    .reset(reset)
  );
  wave23 instance4 (
    .clk(clk),
    .dataout(_3_),
    .reset(reset)
  );
  assign sig_clk_1mhz = _0_;
  assign sig_data2 = _1_;
  assign sig_wave1 = _2_;
  assign sig_wave2 = _3_;
  assign sig_bpsk_out = _4_;
  assign bpsk_out = sig_bpsk_out;
endmodule
