/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

module control_1(reset, clk, sel, demod_0, demod_1, demod_2, demod_data);

  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  reg _6_;
  input clk;
  wire clk;
  input demod_0;
  wire demod_0;
  input demod_1;
  wire demod_1;
  input demod_2;
  wire demod_2;
  output demod_data;
  wire demod_data;
  input reset;
  wire reset;
  input [1:0] sel;
  wire [1:0] sel;
  assign _3_ = _2_ ? demod_2 : 1'h0;
  assign _4_ = _1_ ? demod_1 : _3_;
  assign _5_ = _0_ ? demod_0 : _4_;

  always @(posedge clk, posedge reset)
    if (reset) _6_ <= 1'h0;
    else _6_ <= _5_;
  assign _0_ = sel == 2'h1;
  assign _1_ = sel == 2'h2;
  assign _2_ = sel == 2'h3;
  assign demod_data = _6_;
endmodule
