/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

module demod_bpsk(reset, clk, demod_in, data_demod_bpsk);

  wire [6:0] _0_;
  wire [6:0] _1_;
  wire _2_;
  input clk;
  wire clk;
  output data_demod_bpsk;
  wire data_demod_bpsk;
  input [6:0] demod_in;
  wire [6:0] demod_in;
  input reset;
  wire reset;
  wire [6:0] sig_mult;
  wire [6:0] sig_wave1;

  wave133 instance2 (
    .clk(clk),
    .dataout(_0_),
    .reset(reset)
  );
  mult3 instance3 (
    .a0(demod_in),
    .a1(sig_wave1),
    .clk(clk),
    .mult_out(_1_),
    .reset(reset)
  );
  integrator3 instance5 (
    .clk(clk),
    .comp_in(sig_mult),
    .comp_out(_2_),
    .reset(reset)
  );
  assign sig_wave1 = _0_;
  assign sig_mult = _1_;
  assign data_demod_bpsk = _2_;
endmodule
