/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

module demod_bask(reset, clk, demod_in, demod_out);

  wire _0_;
  wire _1_;
  reg _2_;
  input clk;
  wire clk;
  input [6:0] demod_in;
  wire [6:0] demod_in;
  output demod_out;
  wire demod_out;
  input reset;
  wire reset;

  always @(posedge clk, posedge reset)
    if (reset) _2_ <= 1'h0;
    else _2_ <= _1_;
  assign _0_ = demod_in == 7'h1e;
  assign _1_ = _0_ ? 1'h0 : 1'h1;
  assign demod_out = _2_;
endmodule
