/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

module ffd1(reset, clk, d, q);

  reg _0_;
  reg _1_;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  wire sig_q;
  input reset;
  wire reset;
  
  always @(negedge clk, posedge reset)
    if (reset) _0_ <= 1'h1;
    else _0_ <= d;
  always @(negedge clk)
    _1_ <= sig_q;
  assign sig_q = _0_;
  assign q = _1_;
endmodule
