/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

module modem(reset, clk, sel, mod_out, demod_out);

  wire [6:0] _0_;
  wire [6:0] _1_;
  wire [6:0] _2_;
  wire [6:0] _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  input clk;
  wire clk;
  output demod_out;
  wire demod_out;
  output [6:0] mod_out;
  wire [6:0] mod_out;
  input reset;
  wire reset;
  input [1:0] sel;
  wire [1:0] sel;
  wire [6:0] sig_bask;
  wire [6:0] sig_bfsk;
  wire [6:0] sig_bpsk;
  wire sig_data_demod_0;
  wire sig_data_demod_1;
  wire sig_data_demod_2;

  bask instance1 (
    .bask_out(_0_),
    .clk(clk),
    .reset(reset)
  );
  bfsk instance2 (
    .bfsk_out(_1_),
    .clk(clk),
    .reset(reset)
  );
  bpsk instance3 (
    .bpsk_out(_2_),
    .clk(clk),
    .reset(reset)
  );
  control_0 instance4 (
    .bask_0(sig_bask),
    .bfsk_1(sig_bfsk),
    .bpsk_2(sig_bpsk),
    .clk(clk),
    .mod_out(_3_),
    .reset(reset),
    .sel(sel)
  );
  demod_bask instance6 (
    .clk(clk),
    .demod_in(sig_bask),
    .demod_out(_4_),
    .reset(reset)
  );
  demod_bfsk instance7 (
    .clk(clk),
    .data_demod_bfsk(_5_),
    .demod_in(sig_bfsk),
    .reset(reset)
  );
  demod_bpsk instance8 (
    .clk(clk),
    .data_demod_bpsk(_6_),
    .demod_in(sig_bpsk),
    .reset(reset)
  );
  control_1 instance9 (
    .clk(clk),
    .demod_0(sig_data_demod_0),
    .demod_1(sig_data_demod_1),
    .demod_2(sig_data_demod_2),
    .demod_data(_7_),
    .reset(reset),
    .sel(sel)
  );
  assign sig_bask = _0_;
  assign sig_bfsk = _1_;
  assign sig_bpsk = _2_;
  assign sig_data_demod_0 = _4_;
  assign sig_data_demod_1 = _5_;
  assign sig_data_demod_2 = _6_;
  assign mod_out = _3_;
  assign demod_out = _7_;
endmodule
