/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

module rdg2(reset, clk, data);

  wire _00_;
  wire _01_;
  reg _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [31:0] _08_;
  wire [31:0] _09_;
  reg [31:0] _10_;
  wire a;
  wire b;
  wire c;
  input clk;
  wire clk;
  wire d;
  output data;
  wire data;
  wire [31:0] i;
  input reset;
  wire reset;
  wire sig_data;
  assign _07_ = i == 32'd1;
  assign _08_ = i + 32'd1;
  assign _09_ = _07_ ? 32'd0 : _08_;

  always @(negedge clk, posedge reset)
    if (reset) _10_ <= 32'd0;
    else _10_ <= _09_;
  assign _01_ = _07_ ? sig_data : _02_;
  always @(negedge clk, posedge reset)
    if (reset) _02_ <= 1'h0;
    else _02_ <= _01_;
  assign _06_ = d ^ sig_data;
  ffd2 ffd0 (
    .clk(clk),
    .d(b),
    .q(_03_),
    .reset(reset)
  );
  ffd2 ffd1 (
    .clk(clk),
    .d(a),
    .q(_00_),
    .reset(reset)
  );
  ffd2 ffd3 (
    .clk(clk),
    .d(c),
    .q(_04_),
    .reset(reset)
  );
  ffd2 ffd4 (
    .clk(clk),
    .d(d),
    .q(_05_),
    .reset(reset)
  );
  assign a = _06_;
  assign b = _00_;
  assign c = _03_;
  assign d = _04_;
  assign sig_data = _05_;
  assign i = _10_;
  assign data = _02_;
endmodule
